theme: jekyll-theme-minimal

title: BlenderFDS
description: The open user interface for the</b><a href="https://pages.nist.gov/fds-smv/">NIST Fire Dynamics Simulator (FDS)</a>,</b>a computational fluid dynamics model of fire-driven fluid flow.
logo: https://github.com/firetools/blenderfds/blob/master/logo.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

